import '../models/language.dart';

class LocalizationService {
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      // App Info
      'app_name': 'Houzou Medical',
      'app_subtitle': 'Your Health Partner',
      
      // Authentication
      'welcome_back': 'Welcome Back',
      'create_account': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'full_name': 'Full Name',
      'login': 'Login',
      'register': 'Register',
      'logout': 'Logout',
      'log_in': 'Log In',
      'dont_have_account': "Don't have an account? Register",
      
      // Validation Messages
      'please_enter_email': 'Please enter your email',
      'please_enter_valid_email': 'Please enter a valid email',
      'please_enter_password': 'Please enter your password',
      'password_min_length': 'Password must be at least 6 characters',
      'please_enter_name': 'Please enter your name',
      'please_confirm_password': 'Please confirm your password',
      'passwords_not_match': 'Passwords do not match',
      
      // Success/Error Messages
      'login_successful': 'Login successful!',
      'registration_successful': 'Registration successful!',
      'login_failed': 'Login failed',
      'registration_failed': 'Registration failed',
      'invalid_email_password': 'Invalid email or password',
      'fill_all_fields': 'Please fill all fields correctly',
      
      // Navigation
      'home': 'Home',
      'favorites': 'Favorites',
      'order_history': 'Order History',
      'profile': 'Profile',
      
      // Home Screen
      'search_products': 'Search products...',
      'categories': 'Categories',
      'popular_products': 'Popular Products',
      'see_all': 'See All',
      
      // Categories
      'all': 'All',
      'anti_aging': 'Anti-Aging',
      'sports_nutrition': 'Sports Nutrition',
      'brain_health': 'Brain Health',
      'skin_health': 'Skin Health',
      'general_health': 'General Health',
      'detox_cleanse': 'Detox & Cleanse',
      
      // Product Details
      'description': 'Description',
      'specifications': 'Specifications',
      'reviews': 'Reviews',
      'related_products': 'Related Products',
      'benefits': 'Benefits',
      'key_ingredients': 'Key Ingredients',
      
      // Cart
      'cart': 'Cart',
      'your_cart': 'Your Cart',
      'items_count': '{count} items',
      'checkout': 'Checkout',
      'check_out': 'Check Out',
      'subtotal': 'Subtotal:',
      'total': 'Total:',
      'discount': 'Discount ({code}):',
      'empty_cart': 'Your cart is empty',
      'continue_shopping': 'Continue Shopping',
      'add_voucher_code': 'Add voucher code',
      'voucher_applied': 'Voucher applied: {code}',
      'enter_voucher_code': 'Enter voucher code',
      'apply': 'Apply',
      'voucher_success': 'Voucher applied! You saved {amount}',
      'invalid_voucher': 'Invalid voucher code',
      'voucher_suggestions': 'Try: SAVE10, HEALTH20, FIRST5, WELLNESS15, NEWUSER',
      'delete_item': 'Delete Item',
      'delete_item_confirm': 'Are you sure you want to remove "{item}" from your cart?',
      'delete': 'Delete',
      
      // Checkout/Order
      'order_summary': 'Order Summary',
      'shipping': 'Shipping',
      'free': 'Free',
      'shipping_information': 'Shipping Information',
      'email_address': 'Email Address',
      'phone_number': 'Phone Number',
      'address': 'Address',
      'city': 'City',
      'zip_code': 'ZIP Code',
      'payment_method': 'Payment Method',
      'credit_card': 'Credit Card',
      'credit_card_desc': 'Visa, Mastercard, JCB',
      'paypal': 'PayPal',
      'paypal_desc': 'Pay with your PayPal account',
      'bank_transfer': 'Bank Transfer',
      'bank_transfer_desc': 'Japanese bank transfer',
      'place_order': 'Place Order',
      'order_success_title': 'Order Placed Successfully!',
      'order_success_message': 'Thank you for your order! You will receive a confirmation email shortly.',
      'order_number_display': 'Order Number: {orderNumber}',
      'error_placing_order': 'Error placing order: {error}',
      
      // Order History
      'no_orders_found': 'No orders found',
      'try_adjusting_filters': 'Try adjusting your filters or check back later',
      'filter_orders': 'Filter Orders',
      'date_range': 'Date Range',
      'select_date_range': 'Select date range',
      'clear_date_filter': 'Clear date filter',
      'clear_filter': 'Clear Filter',
      'apply_filter': 'Apply Filter',
      'clear': 'Clear',
      'reorder_items': 'Reorder Items',
      'add_all_items_to_cart': 'Add all items from order #{orderId} to your cart?',
      'add_to_cart': 'Add to Cart',
      'cancel': 'Cancel',
      'reorder_all_items': 'Reorder',
      'items_added_to_cart': '{count} items added to cart',
      'show_more_items': 'Show {count} more items',
      'show_less': 'Show less',
      'items': 'items',
      'each': 'each',
      'order': 'Order',
      'order_number': 'Order #{id}',
      'completed': 'Completed',
      'completed_status': 'Completed',
      
      // Profile
      'please_log_in_profile': 'Please log in to view your profile',
      'edit_profile': 'Edit Profile',
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'addresses': 'Addresses',
      'payment_methods': 'Payment Methods',
      'notifications': 'Notifications',
      'help_support': 'Help & Support',
      'coming_soon': 'Coming Soon',
      'feature_coming_soon': 'This feature is coming soon!',
      'about': 'About',
      'about_app_description': 'Houzou Medical App v1.0.0\n\nYour trusted partner for premium health supplements and wellness products.\n\nBuilt with Flutter',
      'privacy_policy': 'Privacy Policy',
      'terms_service': 'Terms of Service',
      'contact_support': 'Contact Support',
      'version': 'Version',
      'logout_confirmation': 'Are you sure you want to logout?',
      'profile_updated': 'Profile updated!',
      'update_failed': 'Update failed',
      'name': 'Name',
      
      // General
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'retry': 'Retry',
      'save': 'Save',
      'close': 'Close',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      
      // Favorites
      'clear_favorites': 'Clear Favorites',
      'clear_favorites_confirmation': 'Are you sure you want to remove all favorites?',
      'clear_all': 'Clear All',
      'no_favorites_yet': 'No favorites yet',
      'start_adding_favorites': 'Start adding products to your favorites!',
    },
    'ja': {
      // App Info
      'app_name': 'ハウゾウ医療',
      'app_subtitle': 'あなたの健康パートナー',
      
      // Authentication
      'welcome_back': 'おかえりなさい',
      'create_account': 'アカウント作成',
      'email': 'メールアドレス',
      'password': 'パスワード',
      'confirm_password': 'パスワード確認',
      'full_name': '氏名',
      'login': 'ログイン',
      'register': '登録',
      'logout': 'ログアウト',
      'log_in': 'ログイン',
      'dont_have_account': 'アカウントをお持ちでない方は登録',
      
      // Validation Messages
      'please_enter_email': 'メールアドレスを入力してください',
      'please_enter_valid_email': '有効なメールアドレスを入力してください',
      'please_enter_password': 'パスワードを入力してください',
      'password_min_length': 'パスワードは6文字以上で入力してください',
      'please_enter_name': 'お名前を入力してください',
      'please_confirm_password': 'パスワードを確認してください',
      'passwords_not_match': 'パスワードが一致しません',
      
      // Success/Error Messages
      'login_successful': 'ログインが成功しました！',
      'registration_successful': '登録が完了しました！',
      'login_failed': 'ログインに失敗しました',
      'registration_failed': '登録に失敗しました',
      'invalid_email_password': 'メールアドレスまたはパスワードが無効です',
      'fill_all_fields': 'すべての項目を正しく入力してください',
      
      // Navigation
      'home': 'ホーム',
      'favorites': 'お気に入り',
      'order_history': '注文履歴',
      'profile': 'プロフィール',
      
      // Home Screen
      'search_products': '商品を検索...',
      'categories': 'カテゴリー',
      'popular_products': '人気商品',
      'see_all': 'すべて見る',
      
      // Categories
      'all': 'すべて',
      'anti_aging': 'アンチエイジング',
      'sports_nutrition': 'スポーツ栄養',
      'brain_health': '脳の健康',
      'skin_health': '肌の健康',
      'general_health': '一般的な健康',
      'detox_cleanse': 'デトックス・クレンズ',
      
      // Product Details
      'description': '説明',
      'specifications': '仕様',
      'reviews': 'レビュー',
      'related_products': '関連商品',
      'benefits': '効果・効能',
      'key_ingredients': '主要成分',
      
      // Cart
      'cart': 'カート',
      'your_cart': 'あなたのカート',
      'items_count': '{count} 点',
      'checkout': 'チェックアウト',
      'check_out': 'チェックアウト',
      'subtotal': '小計:',
      'total': '合計:',
      'discount': '割引 ({code}):',
      'empty_cart': 'カートが空です',
      'continue_shopping': '買い物を続ける',
      'add_voucher_code': 'クーポンコードを追加',
      'voucher_applied': 'クーポン適用済み: {code}',
      'enter_voucher_code': 'クーポンコードを入力',
      'apply': '適用',
      'voucher_success': 'クーポンが適用されました！{amount}節約できました',
      'invalid_voucher': '無効なクーポンコードです',
      'voucher_suggestions': '試してください: SAVE10, HEALTH20, FIRST5, WELLNESS15, NEWUSER',
      'delete_item': 'アイテムを削除',
      'delete_item_confirm': '「{item}」をカートから削除してもよろしいですか？',
      'delete': '削除',
      
      // Checkout/Order
      'order_summary': '注文概要',
      'shipping': '配送料',
      'free': '無料',
      'shipping_information': '配送先情報',
      'email_address': 'メールアドレス',
      'phone_number': '電話番号',
      'address': '住所',
      'city': '市区町村',
      'zip_code': '郵便番号',
      'payment_method': '支払い方法',
      'credit_card': 'クレジットカード',
      'credit_card_desc': 'Visa、Mastercard、JCB',
      'paypal': 'PayPal',
      'paypal_desc': 'PayPalアカウントで支払い',
      'bank_transfer': '銀行振込',
      'bank_transfer_desc': '日本の銀行振込',
      'place_order': '注文を確定',
      'order_success_title': '注文が正常に完了しました！',
      'order_success_message': 'ご注文ありがとうございます！確認メールを間もなくお送りします。',
      'order_number_display': '注文番号: {orderNumber}',
      'error_placing_order': '注文エラー: {error}',
      
      // Order History
      'no_orders_found': '注文が見つかりません',
      'try_adjusting_filters': 'フィルターを調整するか、後でもう一度確認してください',
      'filter_orders': '注文をフィルター',
      'date_range': '日付範囲',
      'select_date_range': '日付範囲を選択',
      'clear_date_filter': '日付フィルターをクリア',
      'clear_filter': 'フィルタークリア',
      'apply_filter': 'フィルター適用',
      'clear': 'クリア',
      'reorder_items': '商品を再注文',
      'add_all_items_to_cart': '注文 #{orderId} のすべての商品をカートに追加しますか？',
      'add_to_cart': 'カートに追加',
      'cancel': 'キャンセル',
      'reorder_all_items': '再注文',
      'items_added_to_cart': '{count} 個の商品がカートに追加されました',
      'show_more_items': 'さらに {count} 個の商品を表示',
      'show_less': '表示を減らす',
      'items': '個',
      'each': '各',
      'order': '注文',
      'order_number': '注文 #{id}',
      'completed': '完了',
      'completed_status': '完了済み',
      
      // Profile
      'please_log_in_profile': 'プロフィールを表示するにはログインしてください',
      'edit_profile': 'プロフィール編集',
      'settings': '設定',
      'language': '言語',
      'select_language': '言語を選択',
      'addresses': '住所',
      'payment_methods': '支払い方法',
      'notifications': '通知',
      'help_support': 'ヘルプ・サポート',
      'coming_soon': '近日公開',
      'feature_coming_soon': 'この機能は近日公開予定です！',
      'about': '概要',
      'about_app_description': 'ハウゾウ医療アプリ v1.0.0\n\n高品質な健康補助食品とウェルネス製品の信頼できるパートナーです。\n\nFlutterで開発',
      'privacy_policy': 'プライバシーポリシー',
      'terms_service': '利用規約',
      'contact_support': 'サポートに連絡',
      'version': 'バージョン',
      'logout_confirmation': 'ログアウトしてもよろしいですか？',
      'profile_updated': 'プロフィールが更新されました！',
      'update_failed': '更新に失敗しました',
      'name': '名前',
      
      // General
      'loading': '読み込み中...',
      'error': 'エラー',
      'success': '成功',
      'retry': '再試行',
      'save': '保存',
      'close': '閉じる',
      'back': '戻る',
      'next': '次へ',
      'done': '完了',
      'yes': 'はい',
      'no': 'いいえ',
      'ok': 'OK',
      
      // Favorites
      'clear_favorites': 'お気に入りをクリア',
      'clear_favorites_confirmation': 'すべてのお気に入りを削除してもよろしいですか？',
      'clear_all': 'すべてクリア',
      'no_favorites_yet': 'お気に入りがありません',
      'start_adding_favorites': '商品をお気に入りに追加してみましょう！',
    },
    'zh': {
      // App Info
      'app_name': '宝葬医疗',
      'app_subtitle': '您的健康伙伴',
      
      // Authentication
      'welcome_back': '欢迎回来',
      'create_account': '创建账户',
      'email': '邮箱地址',
      'password': '密码',
      'confirm_password': '确认密码',
      'full_name': '姓名',
      'login': '登录',
      'register': '注册',
      'logout': '退出登录',
      'log_in': '登录',
      'dont_have_account': '没有账户？注册',
      
      // Validation Messages
      'please_enter_email': '请输入您的邮箱地址',
      'please_enter_valid_email': '请输入有效的邮箱地址',
      'please_enter_password': '请输入您的密码',
      'password_min_length': '密码至少需要6个字符',
      'please_enter_name': '请输入您的姓名',
      'please_confirm_password': '请确认您的密码',
      'passwords_not_match': '密码不匹配',
      
      // Success/Error Messages
      'login_successful': '登录成功！',
      'registration_successful': '注册成功！',
      'login_failed': '登录失败',
      'registration_failed': '注册失败',
      'invalid_email_password': '邮箱或密码无效',
      'fill_all_fields': '请正确填写所有字段',
      
      // Navigation
      'home': '首页',
      'favorites': '收藏',
      'order_history': '订单历史',
      'profile': '个人资料',
      
      // Home Screen
      'search_products': '搜索产品...',
      'categories': '分类',
      'popular_products': '热门产品',
      'see_all': '查看全部',
      
      // Categories
      'all': '全部',
      'anti_aging': '抗衰老',
      'sports_nutrition': '运动营养',
      'brain_health': '大脑健康',
      'skin_health': '皮肤健康',
      'general_health': '一般健康',
      'detox_cleanse': '排毒清洁',
      
      // Product Details
      'description': '描述',
      'specifications': '规格',
      'reviews': '评价',
      'related_products': '相关产品',
      'benefits': '功效',
      'key_ingredients': '主要成分',
      
      // Cart
      'cart': '购物车',
      'your_cart': '您的购物车',
      'items_count': '{count} 件商品',
      'checkout': '结账',
      'check_out': '结账',
      'subtotal': '小计:',
      'total': '总计:',
      'discount': '折扣 ({code}):',
      'empty_cart': '购物车是空的',
      'continue_shopping': '继续购物',
      'add_voucher_code': '添加优惠券代码',
      'voucher_applied': '优惠券已应用: {code}',
      'enter_voucher_code': '输入优惠券代码',
      'apply': '应用',
      'voucher_success': '优惠券已应用！您节省了 {amount}',
      'invalid_voucher': '无效的优惠券代码',
      'voucher_suggestions': '试试: SAVE10, HEALTH20, FIRST5, WELLNESS15, NEWUSER',
      'delete_item': '删除商品',
      'delete_item_confirm': '您确定要从购物车中删除"{item}"吗？',
      'delete': '删除',
      
      // Checkout/Order
      'order_summary': '订单摘要',
      'shipping': '运费',
      'free': '免费',
      'shipping_information': '配送信息',
      'email_address': '邮箱地址',
      'phone_number': '电话号码',
      'address': '地址',
      'city': '城市',
      'zip_code': '邮政编码',
      'payment_method': '支付方式',
      'credit_card': '信用卡',
      'credit_card_desc': 'Visa、Mastercard、JCB',
      'paypal': 'PayPal',
      'paypal_desc': '使用您的PayPal账户支付',
      'bank_transfer': '银行转账',
      'bank_transfer_desc': '日本银行转账',
      'place_order': '下单',
      'order_success_title': '订单下单成功！',
      'order_success_message': '感谢您的订单！您将很快收到确认邮件。',
      'order_number_display': '订单号: {orderNumber}',
      'error_placing_order': '下单错误: {error}',
      
      // Order History
      'no_orders_found': '未找到订单',
      'try_adjusting_filters': '尝试调整您的筛选条件或稍后再试',
      'filter_orders': '筛选订单',
      'date_range': '日期范围',
      'select_date_range': '选择日期范围',
      'clear_date_filter': '清除日期筛选',
      'clear_filter': '清除筛选',
      'apply_filter': '应用筛选',
      'clear': '清除',
      'reorder_items': '重新订购商品',
      'add_all_items_to_cart': '将订单 #{orderId} 中的所有商品添加到购物车？',
      'add_to_cart': '添加到购物车',
      'cancel': '取消',
      'reorder_all_items': '重新订购',
      'items_added_to_cart': '{count} 件商品已添加到购物车',
      'show_more_items': '显示更多 {count} 件商品',
      'show_less': '显示更少',
      'items': '件',
      'each': '每件',
      'order': '订单',
      'order_number': '订单 #{id}',
      'completed': '已完成',
      'completed_status': '已完成',
      
      // Profile
      'please_log_in_profile': '请登录以查看您的个人资料',
      'edit_profile': '编辑个人资料',
      'settings': '设置',
      'language': '语言',
      'select_language': '选择语言',
      'addresses': '地址',
      'payment_methods': '支付方式',
      'notifications': '通知',
      'help_support': '帮助与支持',
      'coming_soon': '即将推出',
      'feature_coming_soon': '此功能即将推出！',
      'about': '关于',
      'about_app_description': '宝葬医疗应用 v1.0.0\\n\\n高品质健康补充剂和健康产品的可信伙伴。\\n\\n使用Flutter开发',
      'privacy_policy': '隐私政策',
      'terms_service': '服务条款',
      'contact_support': '联系支持',
      'version': '版本',
      'logout_confirmation': '您确定要退出登录吗？',
      'profile_updated': '个人资料已更新！',
      'update_failed': '更新失败',
      'name': '姓名',
      
      // General
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'retry': '重试',
      'save': '保存',
      'close': '关闭',
      'back': '返回',
      'next': '下一步',
      'done': '完成',
      'yes': '是',
      'no': '否',
      'ok': '确定',
      
      // Favorites
      'clear_favorites': '清除收藏',
      'clear_favorites_confirmation': '您确定要删除所有收藏吗？',
      'clear_all': '全部清除',
      'no_favorites_yet': '还没有收藏',
      'start_adding_favorites': '开始添加产品到您的收藏！',
    },
  };

  static String translate(String key, SupportedLanguage language, {Map<String, String>? params}) {
    final translations = _translations[language.code] ?? _translations['en']!;
    String translation = translations[key] ?? key;
    
    // Replace parameters if provided
    if (params != null) {
      params.forEach((paramKey, paramValue) {
        translation = translation.replaceAll('{$paramKey}', paramValue);
      });
    }
    
    return translation;
  }

  static Map<String, String> getAllTranslations(SupportedLanguage language) {
    return _translations[language.code] ?? _translations['en']!;
  }
}